package com.tmax.tibero.hibernate.dialect.identity;

import org.hibernate.dialect.identity.IdentityColumnSupportImpl;
import org.hibernate.generator.EventType;
import org.hibernate.id.insert.GetGeneratedKeysDelegate;
import org.hibernate.persister.entity.EntityPersister;

public class TiberoIdentityColumnSupport extends IdentityColumnSupportImpl {

    public static final TiberoIdentityColumnSupport INSTANCE = new TiberoIdentityColumnSupport();

    /**
     * IDENTITY 컬럼 지원 여부
     * -- true면 이런 컬럼 생성 가능
     * CREATE TABLE users (
     *     id NUMBER GENERATED AS IDENTITY
     * );
     */
    @Override
    public boolean supportsIdentityColumns() {
        return true;
    }

    /**
     * INSERT 문 <b>뒤에 SELECT 를 이어붙여</b> 방금 만든 identity 값을 받아올 수 있는지.
     *
     * <p>{@code true} 면 Hibernate 가 {@link #appendIdentitySelectToInsert}로 조립한
     * 한 덩어리를 실행한다 — SQL Server 의 {@code insert …; select scope_identity()} 가 그 예다.
     * Tibero 는 그 방식 대신 {@code getGeneratedKeys()} 로 회수하므로 {@code false} 다.
     * Hibernate 기본값도 {@code false} 이고 Oracle 역시 오버라이드하지 않는다 —
     * 값을 바꾸려는 게 아니라 <b>판단을 코드에 남기려고</b> 명시했다.
     *
     * <p>⚠️ 이 플래그는 {@code RETURNING … INTO} 지원 여부와 <b>무관하다</b>.
     * Tibero 는 PL/SQL 블록으로 감싸면 {@code returning into} 가 정상 동작한다(실측).
     * 다만 tbjdbc 가 {@code CallableStatement} 로 그 구문을 직접 받지 못해
     * {@code JDBC-90609 Invalid column index} 를 던진다.
     *
     * @see #buildGetGeneratedKeysDelegate 실제로 쓰는 회수 경로
     */
    @Override
    public boolean supportsInsertSelectIdentity() {
        return false;
    }


    /**
     * IDENTITY 컬럼의 DDL 조각.
     *
     * <p>Tibero 는 {@code generated as identity} / {@code generated always as identity} /
     * {@code generated by default as identity} 를 모두 받는다. 앞의 둘은 같은 뜻으로
     * {@code generation_type = ALWAYS} 가 되며, 이때 <b>ID 를 명시한 INSERT 가
     * {@code JDBC-8162} 로 거부된다</b>.
     *
     * <p>6.6.1 까지는 {@code "generated as identity"}(= ALWAYS)를 썼으나
     * {@code by default} 로 바꿨다. 근거는 세 가지다.
     * <ul>
     *   <li>표준 {@code generated … as identity} 문법을 쓰는 Hibernate dialect 6종
     *       (Oracle · PostgreSQL · DB2 · H2 · HANA · HSQL)이 <b>전부</b> {@code by default} 다.
     *       {@code always} 를 쓰는 dialect 는 하나도 없었다.</li>
     *   <li>ALWAYS 는 데이터 이관·시드 스크립트처럼 ID 를 보존해야 하는 작업을 막는다.
     *       애플리케이션은 정상 동작하다가 이관 시점에 실패한다.</li>
     *   <li>DDL 이 바뀌는 변경이라 배포가 쌓일수록 비싸진다 — 6.6.1 출시 전이 가장 싸다.</li>
     * </ul>
     *
     * <p>⚠️ {@code by default} 는 <b>채번 충돌</b>을 동반한다. ID 를 명시해 INSERT 해도
     * 내부 시퀀스는 그것을 모르므로, 이후 자동 채번이 이미 쓴 값을 다시 발급해
     * {@code JDBC-10007 UNIQUE constraint violation} 이 날 수 있다(실측).
     * Oracle · PostgreSQL 에도 있는 함정이며, 명시 삽입 후 시퀀스를 밀어줘야 한다.
     */
    @Override
    public String getIdentityColumnString(int type) {
        return "generated by default as identity";
    }


    /**
     * INSERT 후 생성된 IDENTITY 키를 가져오는 방식
     * - inferredKeys
     * -- false: 컬럼명 명시해서 getGeneratedKeys() 호출 - execute(sql, new String[]{"ID"})
     * -- true: 컬럼명 없이 getGeneratedKeys() 호출 - execute(sql, Statement.RETURN_GENERATED_KEYS)
     * Tibero JDBC는 컬럼명 없이 generated keys를 요청하면 PK가 아니라 ROWID를 반환할 수 있다
     * 따라서 inferredKeys=false로 컬럼명을 명시하도록 한다
     */
    @Override
    public GetGeneratedKeysDelegate buildGetGeneratedKeysDelegate(EntityPersister persister) {
        return new GetGeneratedKeysDelegate(persister, false, EventType.INSERT);
    }

    /**
     * INSERT 시 IDENTITY 컬럼에 넣을 값
     */
    @Override
    public String getIdentityInsertString() {
        return "default";
    }
}
