package com.tmax.tibero.hibernate.dialect.identity;

import org.hibernate.dialect.identity.IdentityColumnSupportImpl;
import org.hibernate.generator.EventType;
import org.hibernate.id.insert.GetGeneratedKeysDelegate;
import org.hibernate.persister.entity.EntityPersister;

/**
 * {@code @GeneratedValue(strategy = IDENTITY)} 컬럼의 DDL 과 생성 키 회수 방식.
 *
 * <pre>
 * DDL     id number(19,0) generated by default as identity
 * 회수    execute(sql, new String[]{"ID"}) → getGeneratedKeys()
 * </pre>
 *
 * <p>회수 때 컬럼명을 명시하는 이유 — tbjdbc 는 컬럼명 없이 생성 키를 요청하면 PK 가 아니라
 * ROWID 를 돌려줄 수 있다. {@link #buildGetGeneratedKeysDelegate} 가 {@code inferredKeys=false}
 * 로 컬럼명을 실어 보낸다.
 */
public class TiberoIdentityColumnSupport extends IdentityColumnSupportImpl {

    public static final TiberoIdentityColumnSupport INSTANCE = new TiberoIdentityColumnSupport();

    /**
     * IDENTITY 컬럼 지원 여부
     * -- true면 이런 컬럼 생성 가능
     * CREATE TABLE users (
     *     id NUMBER GENERATED AS IDENTITY
     * );
     */
    @Override
    public boolean supportsIdentityColumns() {
        return true;
    }

    /**
     * INSERT 문 <b>뒤에 SELECT 를 이어붙여</b> 방금 만든 identity 값을 받아올 수 있는지.
     *
     * <p>{@code true} 면 Hibernate 가 {@link #appendIdentitySelectToInsert}로 조립한
     * 한 덩어리를 실행한다 — SQL Server 의 {@code insert …; select scope_identity()} 가 그 예다.
     * Tibero 는 그 방식 대신 {@code getGeneratedKeys()} 로 회수하므로 {@code false} 다.
     * Hibernate 기본값도 {@code false} 이고 Oracle 역시 오버라이드하지 않는다 —
     * 값을 바꾸려는 게 아니라 <b>판단을 코드에 남기려고</b> 명시했다.
     *
     * <p>⚠️ 이 플래그는 {@code RETURNING … INTO} 지원 여부와 <b>무관하다</b>.
     * Tibero 는 PL/SQL 블록으로 감싸면 {@code returning into} 가 정상 동작한다(실측).
     * 다만 tbjdbc 가 {@code CallableStatement} 로 그 구문을 직접 받지 못해
     * {@code JDBC-90609 Invalid column index} 를 던진다.
     *
     * @see #buildGetGeneratedKeysDelegate 실제로 쓰는 회수 경로
     */
    @Override
    public boolean supportsInsertSelectIdentity() {
        return false;
    }


    /**
     * IDENTITY 컬럼의 DDL 조각.
     *
     * <p>{@code always}(= {@code generated as identity})로 만들면 ID 를 명시한 INSERT 가
     * {@code JDBC-8162} 로 거부되어 이관·시드 스크립트가 막힌다. 그래서 {@code by default}
     * 를 쓴다 — 표준 문법을 쓰는 Hibernate dialect 6종이 전부 그렇다.
     *
     * <p>⚠️ {@code by default} 는 <b>채번 충돌</b>을 동반한다. ID 를 명시해 INSERT 해도 내부
     * 시퀀스는 그것을 모르므로 이후 자동 채번이 이미 쓴 값을 다시 발급해
     * {@code JDBC-10007} 이 날 수 있다(실측). 대응은 {@code docs/user-notes.md} 참고.
     */
    @Override
    public String getIdentityColumnString(int type) {
        return "generated by default as identity";
    }


    /**
     * INSERT 후 생성된 IDENTITY 키를 가져오는 방식
     * - inferredKeys
     * -- false: 컬럼명 명시해서 getGeneratedKeys() 호출 - execute(sql, new String[]{"ID"})
     * -- true: 컬럼명 없이 getGeneratedKeys() 호출 - execute(sql, Statement.RETURN_GENERATED_KEYS)
     * Tibero JDBC는 컬럼명 없이 generated keys를 요청하면 PK가 아니라 ROWID를 반환할 수 있다
     * 따라서 inferredKeys=false로 컬럼명을 명시하도록 한다
     */
    @Override
    public GetGeneratedKeysDelegate buildGetGeneratedKeysDelegate(EntityPersister persister) {
        return new GetGeneratedKeysDelegate(persister, false, EventType.INSERT);
    }

    /**
     * INSERT 시 IDENTITY 컬럼에 넣을 값
     */
    @Override
    public String getIdentityInsertString() {
        return "default";
    }
}
