package audit;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * IDENTITY DDL 을 {@code generated by default as identity} 로 바꾸면서 함께 안내해야 하는
 * 세 가지를 ps06 에서 실측한다. 사용자 안내 문서(§4항)에 싣는 SQL 이 실제로 동작하는지
 * 고정하는 것이 목적이다.
 *
 * <ol>
 *   <li><b>채번 충돌</b> — 명시 ID 를 삽입해도 내부 시퀀스는 그것을 모르므로
 *       이후 자동 채번이 같은 값을 재발급해 {@code JDBC-10007} 이 난다.</li>
 *   <li><b>시퀀스 재조정</b> — Oracle 의 {@code (start with limit value)} 는
 *       {@code JDBC-7008} 로 거부된다. IDENTITY 뒤의 시퀀스를
 *       {@code user_tab_identity_cols.sequence_name} 으로 찾아 <b>증분 점프</b>로 밀어야 한다.</li>
 *   <li><b>기존 ALWAYS 컬럼의 전환</b> — Tibero 는 ALTER 로 전환할 수 없다.
 *       {@code alter table T modify id generated by default as identity} 는
 *       <b>성공을 반환하지만 아무것도 바꾸지 않고</b>, 카탈로그의
 *       {@code generation_type} 만 {@code ERROR} 로 만든다. 테이블 재구성이 유일한 길이다.</li>
 * </ol>
 *
 * <pre>실행: java -cp &lt;test runtime classpath&gt; audit.IdentityMigrationProbe</pre>
 */
public class IdentityMigrationProbe {

    static final String URL = "jdbc:tibero:thin:@localhost:9999:tibero";
    static Connection conn;

    public static void main(String[] args) throws Exception {
        conn = DriverManager.getConnection(URL, "tibero", "tmax");
        conn.setAutoCommit(true);
        try {
            collisionIsReal();
            oracleReseedSyntaxIsRejected();
            sequenceJumpRecipeWorks();
            alterCannotChangeGenerationType();
            tableRebuildIsTheOnlyMigrationPath();
        } finally {
            conn.close();
        }
    }

    // ------------------------------------------------------------------
    // 1. 채번 충돌 — 명시 ID 가 시퀀스 바로 앞을 차지하면 다음 자동 채번이 깨진다
    // ------------------------------------------------------------------
    static void collisionIsReal() {
        System.out.println("=== [1] 채번 충돌 재현 (마지막 insert 가 JDBC-10007 이어야 정상) ===");
        drop("IDP_COLLIDE");
        exec("create table IDP_COLLIDE (id number generated by default as identity primary key, v varchar2(20))");
        exec("insert into IDP_COLLIDE (v) values ('auto1')");            // id=1
        exec("insert into IDP_COLLIDE (id, v) values (2, 'explicit')");  // 시퀀스가 곧 발급할 값
        exec("insert into IDP_COLLIDE (v) values ('auto2')");            // -> JDBC-10007
        dump("결과", "select id, v from IDP_COLLIDE order by id");
        drop("IDP_COLLIDE");
    }

    // ------------------------------------------------------------------
    // 2. Oracle 재조정 구문은 Tibero 에서 전부 거부된다
    // ------------------------------------------------------------------
    static void oracleReseedSyntaxIsRejected() {
        System.out.println();
        System.out.println("=== [2] Oracle 식 시퀀스 재조정 구문 (전부 실패해야 정상) ===");
        drop("IDP_ALTER");
        exec("create table IDP_ALTER (id number generated by default as identity, v varchar2(20))");
        exec("alter table IDP_ALTER modify id generated by default as identity start with limit value");
        exec("alter table IDP_ALTER modify id generated by default as identity (start with limit value)");
        exec("alter table IDP_ALTER modify id generated by default as identity start with 100");
        String seq = scalar("select sequence_name from user_tab_identity_cols where table_name='IDP_ALTER'");
        exec("alter sequence " + seq + " restart with 100");
        drop("IDP_ALTER");
    }

    // ------------------------------------------------------------------
    // 3. 실제로 먹는 방법 — 뒤의 시퀀스를 증분 점프로 민다
    // ------------------------------------------------------------------
    static void sequenceJumpRecipeWorks() {
        System.out.println();
        System.out.println("=== [3] alter sequence 증분 점프 레시피 ===");
        drop("IDP_RESEED");
        exec("create table IDP_RESEED (id number generated by default as identity primary key, v varchar2(20))");

        // 이관: 원래 ID 를 보존하며 적재
        exec("insert into IDP_RESEED (id, v) values (10, 'legacy-10')");
        exec("insert into IDP_RESEED (id, v) values (11, 'legacy-11')");
        exec("insert into IDP_RESEED (id, v) values (12, 'legacy-12')");

        long max = reseed("IDP_RESEED");

        exec("insert into IDP_RESEED (v) values ('after1')");
        exec("insert into IDP_RESEED (v) values ('after2')");
        System.out.println("        기대: " + (max + 1) + ", " + (max + 2) + " 로 이어짐");
        dump("결과", "select id, v from IDP_RESEED order by id");
        drop("IDP_RESEED");
    }

    /** 테이블의 max(id) 다음부터 채번하도록 IDENTITY 뒤 시퀀스를 민다. max(id) 를 돌려준다. */
    static long reseed(String table) {
        String seq = scalar("select sequence_name from user_tab_identity_cols where table_name='" + table + "'");
        long max = Long.parseLong(scalar("select max(id) from " + table));
        // 시퀀스의 현재 위치는 한 번 소비해야만 알 수 있다
        long cur = Long.parseLong(scalar("select " + seq + ".nextval from dual"));
        System.out.println("        시퀀스 " + seq + " / max(id)=" + max + " / 현재값(소비)=" + cur);
        if (max > cur) {
            exec("alter sequence " + seq + " increment by " + (max - cur));
            System.out.println("        점프 후 nextval = " + scalar("select " + seq + ".nextval from dual"));
            exec("alter sequence " + seq + " increment by 1");
        }
        return max;
    }

    // ------------------------------------------------------------------
    // 4. ALWAYS -> BY DEFAULT 전환은 ALTER 로 안 된다 (조용히 무시됨)
    // ------------------------------------------------------------------
    static void alterCannotChangeGenerationType() {
        System.out.println();
        System.out.println("=== [4] ALTER 로 generation_type 을 바꿀 수 있는가 ===");

        System.out.println("  (4a) ALWAYS -> BY DEFAULT : OK 를 반환하지만 실제로는 안 바뀐다");
        drop("IDP_MIG");
        exec("create table IDP_MIG (id number generated as identity primary key, v varchar2(20))");
        genType("IDP_MIG");
        exec("alter table IDP_MIG modify id generated by default as identity");
        genType("IDP_MIG");                                              // -> ERROR
        exec("insert into IDP_MIG (id, v) values (500, 'explicit')");     // -> 여전히 JDBC-8162

        System.out.println("  (4b) identity 를 떼거나 타입을 바꾸는 구문도 없다");
        exec("alter table IDP_MIG modify id drop identity");
        exec("alter table IDP_MIG modify (id drop identity)");
        exec("alter table IDP_MIG modify id number");
        drop("IDP_MIG");

        System.out.println("  (4c) 같은 값으로 ALTER 하면 카탈로그가 깨지지 않는다 — 즉 '변경' 자체가 원인");
        drop("IDP_SAME");
        exec("create table IDP_SAME (id number generated as identity primary key, v varchar2(20))");
        exec("alter table IDP_SAME modify id generated always as identity");
        genType("IDP_SAME");                                             // -> ALWAYS (정상)
        drop("IDP_SAME");

        // 반대 방향은 카탈로그가 똑같이 깨지지만 동작은 바뀐다 —
        // 즉 엔진은 깨진 플래그를 'always' 로 해석한다. 그래서 ALWAYS 에서 벗어날 수만 없다.
        System.out.println("  (4d) BY DEFAULT -> always : 카탈로그는 ERROR 지만 동작은 바뀐다");
        drop("IDP_REV");
        exec("create table IDP_REV (id number generated by default as identity primary key, v varchar2(20))");
        genType("IDP_REV");                                              // -> BY DEFAULT
        exec("alter table IDP_REV modify id generated always as identity");
        genType("IDP_REV");                                              // -> ERROR
        exec("insert into IDP_REV (id, v) values (500, 'explicit')");     // -> JDBC-8162 (거부됨 = 반영됨)
        drop("IDP_REV");
    }

    // ------------------------------------------------------------------
    // 5. 유일하게 되는 길 — 테이블 재구성
    // ------------------------------------------------------------------
    static void tableRebuildIsTheOnlyMigrationPath() {
        System.out.println();
        System.out.println("=== [5] 테이블 재구성으로 전환 ===");
        drop("IDP_OLD");
        drop("IDP_NEW");
        exec("create table IDP_OLD (id number generated as identity primary key, v varchar2(20))");
        exec("insert into IDP_OLD (v) values ('row1')");
        exec("insert into IDP_OLD (v) values ('row2')");

        exec("create table IDP_NEW (id number generated by default as identity primary key, v varchar2(20))");
        exec("insert into IDP_NEW (id, v) select id, v from IDP_OLD");   // 원래 ID 를 보존
        reseed("IDP_NEW");
        exec("drop table IDP_OLD");
        exec("alter table IDP_NEW rename to IDP_OLD");

        genType("IDP_OLD");                                              // -> BY DEFAULT
        exec("insert into IDP_OLD (id, v) values (500, 'explicit')");
        exec("insert into IDP_OLD (v) values ('auto')");
        dump("결과", "select id, v from IDP_OLD order by id");
        drop("IDP_OLD");
    }

    // ------------------------------------------------------------------

    static void exec(String sql) {
        try (Statement s = conn.createStatement()) {
            s.execute(sql);
            System.out.println("  OK    " + sql);
        } catch (SQLException e) {
            System.out.println("  FAIL  " + sql);
            System.out.println("        -> " + firstLine(e));
        }
    }

    static String scalar(String sql) {
        try (Statement s = conn.createStatement(); ResultSet r = s.executeQuery(sql)) {
            return r.next() ? r.getString(1) : "(none)";
        } catch (SQLException e) {
            return "FAIL: " + firstLine(e);
        }
    }

    static void genType(String table) {
        System.out.println("        generation_type(" + table + ") = "
                + scalar("select generation_type from user_tab_identity_cols where table_name='" + table + "'"));
    }

    static void dump(String label, String sql) {
        System.out.println("        " + label + ":");
        try (Statement s = conn.createStatement(); ResultSet r = s.executeQuery(sql)) {
            int cols = r.getMetaData().getColumnCount();
            while (r.next()) {
                StringBuilder b = new StringBuilder("          ");
                for (int i = 1; i <= cols; i++) {
                    b.append(r.getMetaData().getColumnLabel(i)).append('=').append(r.getString(i)).append("  ");
                }
                System.out.println(b);
            }
        } catch (SQLException e) {
            System.out.println("          FAIL -> " + firstLine(e));
        }
    }

    static void drop(String table) {
        try (Statement s = conn.createStatement()) {
            s.execute("drop table " + table);
        } catch (SQLException ignore) {
            // 없으면 그만
        }
    }

    static String firstLine(SQLException e) {
        String m = e.getMessage();
        return m == null ? e.toString() : m.trim().split("\n")[0];
    }
}
