package audit;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import org.hibernate.SessionFactory;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

/**
 * 6.6.0 이 만든 <b>ALWAYS</b> IDENTITY 테이블을 6.6.1 dialect 로 그대로 쓸 수 있는지 확인한다.
 *
 * <p>§4.3 에서 DDL 을 {@code generated by default as identity} 로 바꿨는데,
 * 기존 사용자에게 "ALTER 하지 말고 그대로 써도 된다"고 안내하려면
 * <b>Hibernate 가 IDENTITY 컬럼에 값을 직접 넣는 경로가 정말 없는지</b>를 확인해야 한다.
 * 하나라도 넣는다면 ALWAYS 테이블에서 {@code JDBC-8162} 로 깨진다.
 *
 * <p>테이블은 6.6.0 이 만들었던 모양(ALWAYS)으로 손수 만들고
 * {@code hbm2ddl.auto=none} 으로 붙여, 엔티티 생명주기 전체를 돌린다.
 *
 * <pre>실행: java -cp &lt;test runtime classpath&gt; audit.LegacyAlwaysIdentityProbe</pre>
 */
public class LegacyAlwaysIdentityProbe {

    static final String URL = "jdbc:tibero:thin:@localhost:9999:tibero";
    static final String USER = "tibero";
    static final String PASS = "tmax";

    @Entity(name = "LegacyItem")
    @Table(name = "LGA_ITEM")
    public static class LegacyItem {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        public Long id;
        public String name;
        @Version
        public long ver;
    }

    /** 컬럼이 id 하나뿐인 경우 — Hibernate 가 getIdentityInsertString()="default" 를 쓰는 경로 */
    @Entity(name = "LegacyBare")
    @Table(name = "LGA_BARE")
    public static class LegacyBare {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        public Long id;
    }

    public static void main(String[] args) throws Exception {
        // 같은 생명주기를 두 스키마에 각각 돌려 차이가 IDENTITY 방식 때문인지 가른다
        runAgainst("generated as identity");            // 6.6.0 이 만들던 모양 (ALWAYS)
        runAgainst("generated by default as identity"); // 6.6.1 이 만드는 모양
        cleanup();
    }

    static void runAgainst(String identityClause) throws Exception {
        System.out.println();
        System.out.println("##################################################################");
        System.out.println("### " + identityClause);
        System.out.println("##################################################################");
        prepareSchema(identityClause);

        StandardServiceRegistry registry = new StandardServiceRegistryBuilder()
                .applySetting("hibernate.dialect", "com.tmax.tibero.hibernate.dialect.TiberoDialect")
                .applySetting("hibernate.connection.driver_class", "com.tmax.tibero.jdbc.TbDriver")
                .applySetting("hibernate.connection.url", URL)
                .applySetting("hibernate.connection.username", USER)
                .applySetting("hibernate.connection.password", PASS)
                .applySetting("hibernate.hbm2ddl.auto", "none")   // 기존 스키마를 그대로 쓴다
                .applySetting("hibernate.show_sql", "true")
                .applySetting("hibernate.format_sql", "false")
                .build();

        try (SessionFactory sf = new MetadataSources(registry)
                .addAnnotatedClass(LegacyItem.class)
                .addAnnotatedClass(LegacyBare.class)
                .buildMetadata()
                .buildSessionFactory()) {

            step("persist — IDENTITY 채번", () -> sf.inTransaction(s -> {
                LegacyItem a = new LegacyItem();
                a.name = "first";
                s.persist(a);
                s.flush();
                say("생성된 id = " + a.id);
            }));

            step("연속 persist — 배치 경로", () -> sf.inTransaction(s -> {
                for (int i = 0; i < 3; i++) {
                    LegacyItem e = new LegacyItem();
                    e.name = "bulk-" + i;
                    s.persist(e);
                }
                s.flush();
            }));

            step("find / update / @Version 증가", () -> sf.inTransaction(s -> {
                LegacyItem e = s.createQuery("from LegacyItem order by id", LegacyItem.class)
                        .setMaxResults(1).getSingleResult();
                long before = e.ver;
                e.name = "renamed";
                s.flush();
                say("ver " + before + " -> " + e.ver);
            }));

            step("detached merge — 기존 행", () -> {
                LegacyItem detached = new LegacyItem();
                sf.inTransaction(s -> {
                    LegacyItem e = s.createQuery("from LegacyItem order by id", LegacyItem.class)
                            .setMaxResults(1).getSingleResult();
                    detached.id = e.id;
                    detached.name = "merged";
                    detached.ver = e.ver;
                });
                sf.inTransaction(s -> s.merge(detached));
            });

            step("detached merge — DB 에 없는 id (INSERT 로 떨어지는 경로)", () -> {
                LegacyItem ghost = new LegacyItem();
                ghost.id = 999_999L;              // 존재하지 않는 id 를 들고 있음
                ghost.name = "ghost";
                sf.inTransaction(s -> {
                    LegacyItem managed = s.merge(ghost);
                    s.flush();
                    say("merge 결과 id = " + managed.id + " (요청한 999999 이 아니면 새로 채번된 것)");
                });
            });

            step("컬럼이 id 뿐인 엔티티 — values (default) 경로", () -> sf.inTransaction(s -> {
                LegacyBare b = new LegacyBare();
                s.persist(b);
                s.flush();
                say("생성된 id = " + b.id);
            }));

            step("delete", () -> sf.inTransaction(s -> {
                List<LegacyItem> all = s.createQuery("from LegacyItem", LegacyItem.class).getResultList();
                say("삭제 대상 " + all.size() + "건");
                all.forEach(s::remove);
            }));
        }

        System.out.println();
        System.out.println("=== 명시 ID 를 직접 넣으면? (여기서만 갈린다) ===");
        try (Connection c = DriverManager.getConnection(URL, USER, PASS)) {
            exec(c, "insert into LGA_ITEM (id, name, ver) values (500, 'manual', 0)");
        }
    }

    // ------------------------------------------------------------------

    static void prepareSchema(String identityClause) throws SQLException {
        try (Connection c = DriverManager.getConnection(URL, USER, PASS)) {
            drop(c, "LGA_ITEM");
            drop(c, "LGA_BARE");
            exec(c, "create table LGA_ITEM ("
                    + "id number(19,0) " + identityClause + ", "
                    + "name varchar2(255), ver number(19,0) not null, primary key (id))");
            exec(c, "create table LGA_BARE (id number(19,0) " + identityClause + ", primary key (id))");
            System.out.println("  generation_type = " + scalar(c,
                    "select generation_type from user_tab_identity_cols where table_name='LGA_ITEM'"));
        }
    }

    static void cleanup() throws SQLException {
        try (Connection c = DriverManager.getConnection(URL, USER, PASS)) {
            drop(c, "LGA_ITEM");
            drop(c, "LGA_BARE");
        }
    }

    interface Block { void run(); }

    static void step(String label, Block b) {
        System.out.println();
        System.out.println("=== " + label + " ===");
        try {
            b.run();
            System.out.println("  -> OK");
        } catch (RuntimeException e) {
            Throwable root = e;
            while (root.getCause() != null) {
                root = root.getCause();
            }
            System.out.println("  -> FAIL  " + root.getClass().getSimpleName() + ": "
                    + String.valueOf(root.getMessage()).trim().split("\n")[0]);
        }
    }

    static void say(String s) {
        System.out.println("  " + s);
    }

    static void exec(Connection c, String sql) {
        try (Statement s = c.createStatement()) {
            s.execute(sql);
            System.out.println("  OK    " + sql);
        } catch (SQLException e) {
            System.out.println("  FAIL  " + sql);
            System.out.println("        -> " + e.getMessage().trim().split("\n")[0]);
        }
    }

    static String scalar(Connection c, String sql) {
        try (Statement s = c.createStatement(); ResultSet r = s.executeQuery(sql)) {
            return r.next() ? r.getString(1) : "(none)";
        } catch (SQLException e) {
            return "FAIL: " + e.getMessage().trim().split("\n")[0];
        }
    }

    static void drop(Connection c, String table) {
        try (Statement s = c.createStatement()) {
            s.execute("drop table " + table);
        } catch (SQLException ignore) {
            // 없으면 그만
        }
    }
}
