package integration;

import support.AbstractTiberoDialectTestBase;
import support.SqlCaptureInspector;
import com.tmax.tibero.hibernate.dialect.identity.TiberoIdentityColumnSupport;
import jakarta.persistence.*;

import org.hibernate.cfg.Configuration;
import org.hibernate.dialect.Dialect;
import org.hibernate.engine.spi.SessionFactoryImplementor;
import org.hibernate.id.insert.GetGeneratedKeysDelegate;
import org.hibernate.persister.entity.EntityPersister;
import org.junit.Before;
import org.junit.Test;

import java.sql.*;
import java.util.Locale;

import static org.junit.Assert.*;

/**
 * IdentityColumnSupportTest
 *
 * 목적:
 *  - IdentityColumnSupportTest의 contract 테스트
 *  - 실제 Tibero DB에서 IDENTITY 컬럼이 생성되고
 *    Hibernate가 INSERT 후 generated key를 정상적으로 가져오는지 검증
 */
public class IdentityColumnSupportTest extends AbstractTiberoDialectTestBase {

    private SessionFactoryImplementor sfi;
    private Dialect dialect;
    private TiberoIdentityColumnSupport identitySupport;

    @Override
    protected Class<?>[] getAnnotatedClasses() {
        return new Class<?>[] { IdentityEntity.class };
    }

    @Override
    protected void configure(Configuration cfg) {
        super.configure(cfg);
        cfg.setProperty("hibernate.hbm2ddl.auto", "create-drop");
        cfg.setProperty("hibernate.session_factory.statement_inspector", SqlCaptureInspector.class.getName());
    }

    @Before
    public void setUp() {
        sfi = sessionFactory();
        dialect = sfi.getJdbcServices().getDialect();
        assertNotNull(dialect);

        identitySupport = (TiberoIdentityColumnSupport) dialect.getIdentityColumnSupport();
        assertNotNull(identitySupport);

        SqlCaptureInspector.clear();
    }

    // =========================================================================
    // 1) Unit / Contract tests
    // =========================================================================

    @Test
    public void contract_supportsIdentityColumns_true() {
        assertTrue(identitySupport.supportsIdentityColumns());
    }

    @Test
    public void contract_supportsInsertSelectIdentity_isFalse() {
        // INSERT 뒤에 SELECT 를 이어붙이는 방식(SQL Server 의 scope_identity() 류)을 쓰지 않는다는 뜻.
        // Tibero 는 getGeneratedKeys() 로 회수한다. Hibernate 기본값도 false 이고 Oracle 도 동일하다.
        assertFalse(identitySupport.supportsInsertSelectIdentity());
    }

    @Test
    public void contract_identityColumnString_isGeneratedByDefault() {
        // ALWAYS 로 되돌아가면 ID 를 명시한 INSERT 가 JDBC-8162 로 거부된다 —
        // 데이터 이관·시드 스크립트가 막히므로 by default 를 유지해야 한다.
        assertEquals("generated by default as identity",
                identitySupport.getIdentityColumnString(Types.BIGINT).toLowerCase(Locale.ROOT));
    }

    /**
     * DDL 문자열뿐 아니라 <b>DB 가 실제로 BY DEFAULT 로 만들었는지</b>까지 본다.
     *
     * <p>{@code generated as identity} 와 {@code generated always as identity} 는 둘 다
     * {@code ALWAYS} 가 되므로, 문자열만 검사하면 의미가 뒤집혀도 못 잡는다.
     */
    @Test
    public void integration_identityColumn_isByDefaultNotAlways() {
        String type = inTransactionReturning(session -> session.createNativeQuery(
                "select generation_type from user_tab_identity_cols "
                        + "where table_name='IDENTITY_TEST' and column_name='ID'",
                String.class).getSingleResult());
        assertEquals("ALWAYS 면 명시 ID INSERT 가 막힘", "BY DEFAULT", type.trim().toUpperCase(Locale.ROOT));
    }

    /**
     * {@code by default} 로 바꾼 <b>목적</b> — ID 를 명시한 INSERT 가 통해야 한다.
     *
     * <p>데이터 이관·시드 스크립트·덤프 복원이 이 경로를 쓴다. ALWAYS 였을 때는
     * {@code JDBC-8162 Cannot insert into an always identity column} 으로 막혔다.
     */
    @Test
    public void integration_explicitIdInsert_isAllowed() {
        inTransaction(session -> session.createNativeMutationQuery(
                "insert into identity_test (id, name) values (999, 'migrated')").executeUpdate());

        Long found = inTransactionReturning(session -> session.createNativeQuery(
                "select id from identity_test where name='migrated'", Long.class).getSingleResult());
        assertEquals("ID 를 보존한 INSERT 가 통해야 함", Long.valueOf(999L), found);
    }

    @Test
    public void contract_identityInsertString_isDefault() {
        assertEquals("default", identitySupport.getIdentityInsertString().toLowerCase(Locale.ROOT));
    }

    /**
     * identitySupport.buildGetGeneratedKeysDelegate()
     * - GetGeneratedKeysDelegate 내부가 너무 깊어서 mock persister로는 객체 생성 자체가 안되기 때문에 Integration test로 대체
     */

    // =========================================================================
    // 2) Integration test: IDENTITY 컬럼 생성 + insert + generated key retrieval
    // =========================================================================

    @Test
    public void integration_identityInsert_generatesIdAndRetrievesGeneratedKey() {
        assertSame(TiberoIdentityColumnSupport.INSTANCE, dialect.getIdentityColumnSupport());

        Long id = inTransactionReturning(session -> {
            IdentityEntity e = new IdentityEntity();
            e.setName("hello");
            session.persist(e);
            session.flush(); // insert 발생

            assertNotNull("ID should be assigned after flush", e.getId());
            return e.getId();
        });

        assertNotNull("Generated id must not be null", id);

        // 실제 row 존재 확인
        inTransaction(session -> {
            IdentityEntity found = session.find(IdentityEntity.class, id);
            assertNotNull(found);
            assertEquals("hello", found.getName());
        });
    }

    /**
     * getIdentityInsertString()
     *
     * Hibernate가 생성한 INSERT SQL이 identity 컬럼(id)을 직접 넣지 않고
     * name만 넣는지(혹은 default 키워드로 넣는지) 확인
     *
     * DB마다 id 컬럼 포함 여부가 다를 수 있어도,
     * 최소한 TiberoIdentityColumnSupport.getIdentityInsertString() == "default" 이므로
     * id에 default를 넣는 형태도 acceptable.
     */
    @Test
    public void integration_insertSql_doesNotManuallyAssignIdentityValue() {
        SqlCaptureInspector.clear();

        inTransaction(session -> {
            IdentityEntity e = new IdentityEntity();
            e.setName("sql-check");
            session.persist(e);
            session.flush();
        });

        String insertSql = SqlCaptureInspector.getSqls().stream()
                .map(String::toLowerCase)
                .filter(sql -> sql.startsWith("insert into identity_test"))
                .findFirst()
                .orElse(null);

        assertNotNull("INSERT SQL should be captured", insertSql);

        // 두 형태 모두 허용:
        // 1) insert into IDENTITY_TEST (NAME) values (?)
        // 2) insert into IDENTITY_TEST (ID, NAME) values (default, ?)
        boolean containsIdColumn = insertSql.contains("(id,") || insertSql.contains(",id)");
        if (containsIdColumn) {
            assertTrue(
                    "If id column is present, it must use DEFAULT keyword",
                    insertSql.contains("default")
            );
        }
    }

    /**
     * supportsIdentityColumns()
     *
     * 실제 테이블 컬럼이 generated as identity 로 생성됐는지 dictionary에서 확인
     * Tibero는 user_tab_cols에 identity 컬럼 정보가 노출될 수 있음.
     * (만약 Tibero 버전에 따라 컬럼이 다르면, 이 테스트는 옵션으로 처리 가능)
     */
    @Test
    public void integration_identityColumnExistsInDictionary() {
        inTransaction(session -> {
            // Tibero 버전에 따라 컬럼 정보가 다를 수 있음.
            // user_tab_cols / user_tab_identity_cols 등 확인 필요
            long count = session.createNativeQuery(
                    "select count(*) from user_tab_identity_cols where table_name = 'IDENTITY_TEST' and column_name = 'ID'",
                    Long.class
            ).getSingleResult();

            assertEquals("ID column must exist", 1L, count);
        });
    }

    /**
     * {@code returning … into} 를 <b>CallableStatement 로 직접</b> 쓰면 드라이버가 거부한다.
     *
     * <p><b>Tibero 가 그 구문을 못 쓰는 것이 아니다</b> — PL/SQL 블록으로 감싸면 정상 동작한다
     * (아래 두 번째 케이스). 막히는 것은 tbjdbc 가 벌거벗은 DML + OUT 파라미터 조합을
     * 받지 못하는 것뿐이며 {@code JDBC-90609 Invalid column index} 를 던진다.
     *
     * <p>그래서 dialect 는 이 경로 대신 {@code getGeneratedKeys()} 를 쓴다
     * ({@link org.hibernate.dialect.identity.IdentityColumnSupport#buildGetGeneratedKeysDelegate}).
     * 이 테스트는 <b>그 선택의 전제</b>를 고정한다 — 드라이버가 받아주기 시작하면 여기서 먼저 깨진다.
     */
    @Test
    public void returningIntoViaCallableStatement_isRejectedByDriver() {
        inSession(session -> session.doWork(conn -> {
            // ① 벌거벗은 DML + OUT 파라미터 → 드라이버가 거부
            try (CallableStatement cs = conn.prepareCall(
                    "insert into identity_test (name) values (?) returning id into ?")) {
                cs.setString(1, "john");
                cs.registerOutParameter(2, java.sql.Types.BIGINT);
                cs.executeUpdate();
                fail("드라이버가 이 형태를 받기 시작했다면 dialect 의 회수 경로 선택을 재검토할 것");
            } catch (SQLException e) {
                assertEquals("거부 사유가 바뀌면 전제가 달라진 것 — 원인을 다시 확인할 것",
                        -90609, e.getErrorCode());
            }

            // ② PL/SQL 블록으로 감싸면 Tibero 는 returning into 를 정상 처리한다
            try (CallableStatement cs = conn.prepareCall(
                    "begin insert into identity_test (name) values (?) returning id into ?; end;")) {
                cs.setString(1, "jane");
                cs.registerOutParameter(2, java.sql.Types.BIGINT);
                cs.executeUpdate();
                assertTrue("PL/SQL 블록 경로는 동작해야 함 — Tibero 자체는 returning into 를 지원함",
                        cs.getLong(2) > 0);
            }
        }));
    }

    /**
     * buildGetGeneratedKeysDelegate()
     * - generated key retrieval delegate 생성 테스트
     */
    @Test
    public void testBuildGetGeneratedKeysDelegate_generatedKeyRetrievalWorks() {
        // 1) persister를 real runtime metamodel에서 구한다 (mock 불가)
        EntityPersister persister =
                sfi.getRuntimeMetamodels()
                        .getMappingMetamodel()
                        .getEntityDescriptor(IdentityEntity.class.getName());

        assertNotNull(persister);

        // 2) delegate 생성 가능해야 함
        GetGeneratedKeysDelegate delegate = identitySupport.buildGetGeneratedKeysDelegate(persister);
        assertNotNull(delegate);

        // 3) 실제로 Hibernate가 generated key retrieval 성공하는지
        Long id = inTransactionReturning(session -> {
            IdentityEntity e = new IdentityEntity();
            e.setName("delegate-test");
            session.persist(e);
            session.flush();

            assertNotNull("ID should be generated by GetGeneratedKeysDelegate", e.getId());
            return e.getId();
        });

        assertNotNull(id);

        // 4) inferredKeys parameter (success)
        inSession(session -> session.doWork(conn -> {
            String sql = "insert into identity_test (name) values (?)";

            try (PreparedStatement ps = conn.prepareStatement(sql, new String[]{"ID"})) {
                ps.setString(1, "a");
                int updated = ps.executeUpdate();
                assertEquals(1, updated);

                try (ResultSet keys = ps.getGeneratedKeys()) {
                    assertTrue("GeneratedKeys must have a row", keys.next());
                    long generatedId = keys.getLong(1);
                    assertTrue("Generated id should be > 0", generatedId > 0);
                }
            }
        }));
    }

    // =========================================================================
    // Test Entity
    // =========================================================================
    @Entity(name = "IdentityEntity")
    @Table(name = "IDENTITY_TEST")
    public static class IdentityEntity {

        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        private Long id;

        @Column(name = "NAME")
        private String name;

        public Long getId() { return id; }

        public String getName() { return name; }

        public void setName(String name) { this.name = name; }
    }
}
